###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-cp4a-operator
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 21.0.3
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - restricted
  verbs:
  - use
  - list

- apiGroups:
  - icp4a.ibm.com
  resources:
  - '*'
  verbs:
  - '*'

- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - '*'

- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - '*'

- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get

- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - list

- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - create
  - patch
  - update
  - delete

# for one-click to send operand request to ibm-common-services
- apiGroups:
  - operator.ibm.com
  resources:
  - operandrequests
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch

- apiGroups:
  - operator.ibm.com
  resources:
  - operandrequests/status
  verbs:
    - get

- apiGroups:
  - operator.openshift.io
  resources:
  - ingresscontrollers
  verbs:
    - get

- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  - clusterserviceversions
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch

- apiGroups:
  - db2u.databases.ibm.com
  resources:
  - db2uclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - db2u.databases.ibm.com/v1
  resources:
  - db2uclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - db2u.databases.ibm.com/v1.Db2uCluster
  resources:
  - db2uclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - operator.ibm.com
  resources:
  - businessteamsservices
  verbs:
  - '*'

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - delete
- apiGroups:
  - apiextensions.k8s.io
  verbs:
  - get
  - list
  resources:
  - customresourcedefinitions